### ISSUE TITLE
May I please quote your webpages into my app?

### ISSUE THREAD

**Issue by shinoyasan** [sparrowhe/new-aip#2]
I am a developer of fsu, having finished and deployed our route-finder website online(codes are in my repository). 

We are now developing an offline AIP viewer client on windows and linux, and I'd like to quote your webpage code in folder 'new-aip/public' into our front-end program which uses the framework of **electron** and node.js to build the structure.

As you know, electron is a UI framework allowing us to use HTML to decide what the client looks like. We plan to **just quote your HTML files** and do some changes in order to fit the client. **We will still follow GPL2.0 and do a pull request to this repository after our work.**

Now we are wondering your attitude, and we'll appreciate it if you agree and be in favor of our plan.

**Comment by sparrowhe** [comment]
All right. Fell free to use it. Please follow GPLv2.0 license. 👍

**Comment by sparrowhe** [comment]
BTW, Database in ERC charts and the AD part of AIP on OSS are NOT allow to use. Is not was made by me. If you need, you can contact me on QQ, and I will give you AD part's pdf every AIP cycle. You should upload them to your own server.

**Comment by shinoyasan** [comment]
Thank you very much. We will make it according to your suggestions.

**Comment by sparrowhe** [comment]
If you have any question about this, please reopen this issue. I will close it now.
